# Generated by Django 4.0.4 on 2022-05-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('life', models.CharField(max_length=50)),
            ],
        ),
    ]
